apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: event-sourcing-service
spec:
  selector:
    matchLabels:
      app: event-sourcing-service
  replicas: 1 # Number of replicas that will be created for this deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: event-sourcing-service
    spec:
      containers:
        - name: event-sourcing-service
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069 # The port that the container is running on in the cluster
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m